---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes
  serial: 30%

  vars:
    etherpad_port: 9002

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.npm
    - role: ansible-role-etherpad
